### PR TITLE
modularize

### LINKED ISSUE #2: Migrate to Nix
Use haskellNix for Haskell package management instead of cabal. This will help prepare for packaging in nixpkgs and deployment as NixOS module via flake.

### PR DESCRIPTION
**Pull request by quantum9Innovation**

### CODE REVIEW

**Comment by youwen5** [comment]
Should migrate to package management purely through nix to prepare for packaging in nixpkgs and deployment as NixOS flake. This is a blocking issue that needs to be resolved before merging. See #2.

**Comment by youwen5** [comment]
I've added a flake and successfully tested using `nix build` and `nix run`. Other code changes look good, test the Nix flake and merge when ready :+1: :shipit:

Closes #2

**Review by youwen5 — DISMISSED** [review]

**Comment by youwen5** [comment]
CI tests passing, ready to merge.

**Review by quantum9Innovation — COMMENTED** [review]
Aight, lgtm :shipit:[^1]

[^1]: On a more theoretical note, it is necessary to include `at` not as a build-time dependency, but as a runtime dependency, since this is the whole point of Nix (more on this in a future issue)

**Review by youwen5 — APPROVED** [review]

**Comment by quantum9Innovation** [comment]
Shipped

**Pull request merged**
